### ISSUE TITLE
Nuget Organization

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-members-client-dotnet#5]
I just found the nuget package for this: https://www.nuget.org/packages/BccMembers.Api.Client.Contracts/
Long term it would be nice if this package can be transfer to the bcc organization: https://www.nuget.org/profiles/bcc-code

**Comment by tkristiansen** [comment]
Agree. Who has the deployment key for that? Can it maybe be added as a secret to this repository?

**Comment by kkuepper** [comment]
Reng and Me have control over that account. If I understand it correctly the API keys are limited to specific packages. That means I can't create a key before the package has been transfered.
@tkristiansen If you tell me your nuget user, I can add you to the organization, then you can do it.

**Comment by tkristiansen** [comment]
Ok. My nuget user is tkristiansen84.

Best regards,
Terje Kristiansen

[Text, logo  Description automatically generated]

Mobile (DE): +49 170 8507188
Mobile (NO): +47 919 29 206
***@***.******@***.***> | capenda.com<http://www.capenda.com/>

**Comment by tkristiansen** [comment]
@yuriy-butkevych, can you please transfer the nuget packages to my account? I can then fix the rest.

**Comment by tkristiansen** [comment]
Packages transferred to nuget.org bcc-code organization and API key used from this repository updated.
